[package]
name = "bike_physics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["dynamic_linking", "bevy_dev_tools", "bevy_pbr"] }
rapier3d = "0.30.1"

[profile.dev.package."*"]
opt-level = 3
